# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 355988890be531f6aaf4cc40597c84ab6e0e86bd23439e173cb923ad3cff39e84f48c56cbb7bc6b923682a5f561da5c944238ca47b3cc46dcc08e8e82b98259d

test:
  secret_key_base: 09cb0abda97aec760390dc543408902d96fccc5b6a2cb9cd484e1002438418d19002790f1744f28e4fb5239315c4691a8781f8c13cf07c578d7452a6e84c222d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
